In [6]:
import numpy as np

matriz = np.array(
  [
    [2,-5,-11,0],
    [-9,4,6,13],
    [4,7,12,-2]
  ]
)
print(matriz)
print(matriz[1][1])
print(matriz[1][3])
print(matriz[0][2])

[[  2  -5 -11   0]
 [ -9   4   6  13]
 [  4   7  12  -2]]
4
13
-11


In [9]:
lista = [
  [2,-5,-11,0],
  [-9,4,6,13],
  [4,7,12,-2]
]
matriz = np.array(lista)
print(matriz)

print(lista[1][3])
print(matriz[1][3])

[[  2  -5 -11   0]
 [ -9   4   6  13]
 [  4   7  12  -2]]
13
13


In [11]:
matriz = np.array(
  [
    [2,-5,-11,0],
    [-9,4,6,13],
    [4,7,12,-2]
  ]
)

print(matriz[0][3])
print(matriz[0,3])

0
0
2
-5
-11
0
-9
4
6
13
4
7
12
-2


In [15]:
for fila in matriz:
  for celda in fila:
    print(celda)

2
-5
-11
0
-9
4
6
13
4
7
12
-2


In [17]:
for i in range(len(matriz)):
  for j in range(len(matriz[i])):
    print(f"({i},{j}): {matriz[i,j]}")

(0,0): 2
(0,1): -5
(0,2): -11
(0,3): 0
(1,0): -9
(1,1): 4
(1,2): 6
(1,3): 13
(2,0): 4
(2,1): 7
(2,2): 12
(2,3): -2


In [21]:
ejemplo = np.array([
      [
       [1],[2]
      ],
      [
       [3],[4]
      ]
    ])
print(ejemplo)
print(ejemplo.ndim)

[[[1]
  [2]]

 [[3]
  [4]]]
3
