Crear dos arreglos de dos dimensiones de tamaño 3 x 3, con elementos de tipo numérico entero, luego:
Muestra la matriz 1.
Muestra la matriz 2.
Muestre la matriz resultante de la multiplicación de la matriz 1 y matriz 2.


In [ ]:
import numpy as np

#matriz1 = np.array([[0,0,0],[0,0,0], [0,0,0]])
matriz1 = np.ones((3,3))
matriz2 = np.random.randint(9, size=(3,3))
print(matriz1)
print(matriz2)
# print(type(matriz1[0][0])) # porque sae el 1 con un punto

print(matriz1*matriz2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 6 8]
 [8 4 6]
 [8 4 5]]
[[7. 6. 8.]
 [8. 4. 6.]
 [8. 4. 5.]]


In [ ]:
val1=268.0
val2=0.0125
mult=val1*val2
print(mult)

3.35


Crear un arreglo de dos dimensiones de tamaño 10 y 4,  el cual, simula a un bus. 
Se pide asignar los números de asiento en forma automática, considerando el siguiente formato:
 
1	2		3	4
5	6		7	8
9	10		11	12
13	14		15	16
17	18		19	20
21	22		23	24
25	26		27	28
29	30		31	32
33	34		35	36
37	38		39	40

In [ ]:
bus = np.zeros((10,4))

contador = 1
for i in range(len(bus)):
  for j in range(len(bus[i])):
    bus[i][j] = contador
    contador += 1

print(bus)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]
 [33. 34. 35. 36.]
 [37. 38. 39. 40.]]


Otra forma de hacerlo menos "programaticamente"

```
bus = [
       [1,2,3,4],
       [5,6,7,8]
       ....
]
```



Crear un arreglo de dos dimensiones de tamaño 4 y 5, con elementos aleatorios de números enteros del 0 al 100, luego:



* Mostrar por pantalla la suma de los  elementos de cada fila.
* Mostrar por pantalla la suma de los elementos de cada columna.
* Mostrar por pantalla la suma de los elementos de la diagonal principal.
* Mostrar por pantalla la cantidad de elementos impares.


In [ ]:
import numpy as np

# arreglo de dos dimensiones de tamaño 4 y 5 
# con elementos aleatorios de números enteros del 0 al 100,
arreglo = np.random.randint(100, size=(4,5))
print(arreglo)

for fila in arreglo:
  print(sum(fila))

[[ 1 19  9 55 23]
 [53 22 43 98 94]
 [78 70 64  9 78]
 [43 41 32 86 73]]
107
310
299
275


In [ ]:
for i in range(5):
  print(sum(arreglo[:, i]))

227
267
192
190
135


In [ ]:
acumulador = 0
for i in range(4):
  acumulador += arreglo[i][i]
print(acumulador)

182


In [ ]:
contador_impares = 0

for filas in arreglo:
  for celda in fila:
    if celda % 2 != 0:
      contador_impares += 1
print(contador_impares)

12
